"""
pipeline/prepare.py

Downloads the RDD2022ES dataset from KaggleHub and formats it for YOLO:

    dataset_yaml/
        images/train/   ← .jpg
        images/val/     ← .jpg
        labels/train/   ← .txt
        labels/val/     ← .txt
        data.yaml       ← auto-generated
"""

import os
import random
import shutil
import kagglehub

import filehandler as fh


def _find_source_dirs(kaggle_path):
    """
    Walk the KaggleHub download and return (img_dir, lbl_dir).
    Handles arbitrarily nested unpack structures.
    """
    img_dir = lbl_dir = None
    for dirpath, _, filenames in os.walk(kaggle_path):
        if img_dir is None and any(f.lower().endswith(".jpg") for f in filenames):
            img_dir = dirpath
        if lbl_dir is None and any(
            f.lower().endswith(".txt") and f != "classes.txt" for f in filenames
        ):
            lbl_dir = dirpath
        if img_dir and lbl_dir:
            break
    return img_dir, lbl_dir


def _get_class_names(img_dir, lbl_dir):
    """
    Read class names from classes.txt, or infer them from label file contents.
    """
    for candidate_dir in (img_dir, lbl_dir):
        if candidate_dir is None:
            continue
        classes_txt = os.path.join(candidate_dir, "classes.txt")
        if os.path.exists(classes_txt):
            with open(classes_txt) as f:
                names = [line.strip() for line in f if line.strip()]
            if names:
                return names

    print("WARNING: classes.txt not found — inferring class IDs from label files.")
    ids = set()
    if lbl_dir:
        for fn in os.listdir(lbl_dir):
            if fn.lower().endswith(".txt") and fn != "classes.txt":
                with open(os.path.join(lbl_dir, fn)) as f:
                    for line in f:
                        parts = line.split()
                        if parts:
                            ids.add(int(parts[0]))
    return [f"class{i}" for i in sorted(ids)] if ids else ["defect"]


def _copy_split(image_list, split_name, src_img_dir, src_lbl_dir):
    """Copy images and labels into their train/ or val/ destinations."""
    missing = []
    for img_name in image_list:
        stem     = os.path.splitext(img_name)[0]
        lbl_name = stem + ".txt"

        shutil.copy2(
            os.path.join(src_img_dir, img_name),
            os.path.join(fh.IMAGE_DIR, split_name, img_name),
        )

        if src_lbl_dir:
            src_lbl = os.path.join(src_lbl_dir, lbl_name)
            dst_lbl = os.path.join(fh.LABEL_DIR, split_name, lbl_name)
            if os.path.exists(src_lbl):
                shutil.copy2(src_lbl, dst_lbl)
            else:
                missing.append(img_name)
                open(dst_lbl, "w").close()  # empty file so YOLO doesn't complain

    if missing:
        print(f"  WARNING: {len(missing)} image(s) in '{split_name}' had no label — empty files created:")
        for name in missing:
            print(f"    - {name}")


def _write_yaml(class_names):
    """Write data.yaml into dataset_yaml/."""
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(class_names))
    content = (
        f"# Auto-generated by pipeline/prepare.py\n"
        f"path: {fh.DATASET_DIR}\n\n"
        f"train: images/train\n"
        f"val:   images/val\n\n"
        f"nc: {len(class_names)}\n"
        f"names:\n{names_block}\n"
    )
    with open(fh.DATA_YAML, "w") as f:
        f.write(content)
    print(f"data.yaml written to: {fh.DATA_YAML}")


def run():
    """Download and prepare the RDD2022ES dataset."""

    # 1. Download
    print("Downloading RDD2022ES from KaggleHub ...")
    kaggle_path = kagglehub.dataset_download("juusos/rdd2022es")
    print(f"Downloaded to: {kaggle_path}\n")

    for root, _, files in os.walk(kaggle_path):
        print(root)
        for f in files:
            print("    ", f)

    # 2. Locate source dirs
    src_img_dir, src_lbl_dir = _find_source_dirs(kaggle_path)
    if src_img_dir is None:
        raise RuntimeError(
            f"Could not find any .jpg files under {kaggle_path}.\n"
            "Check the directory listing printed above."
        )
    print(f"\nSource images : {src_img_dir}")
    print(f"Source labels : {src_lbl_dir}")

    # 3. Discover classes
    class_names = _get_class_names(src_img_dir, src_lbl_dir)
    print(f"Classes ({len(class_names)}): {class_names}")

    # 4. Split
    random.seed(fh.RANDOM_SEED)
    images = sorted(f for f in os.listdir(src_img_dir) if f.lower().endswith(".jpg"))
    random.shuffle(images)
    split        = int(len(images) * fh.TRAIN_RATIO)
    train_images = images[:split]
    val_images   = images[split:]

    # 5. Copy
    print("\nPreparing training set ...")
    _copy_split(train_images, "train", src_img_dir, src_lbl_dir)

    print("Preparing validation set ...")
    _copy_split(val_images, "val", src_img_dir, src_lbl_dir)

    # 6. Write data.yaml
    _write_yaml(class_names)

    # 7. Summary
    print(f"\nTraining images   : {len(train_images)}")
    print(f"Validation images : {len(val_images)}")
    print("\nDataset preparation complete!")
